spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpabasic
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug

# C:\'Program Files (x86)'\H2\bin
# jdbc:h2:mem:test
