spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    #open-in-view: false

  h2:
    console:
      enabled: true

logging.level:
    org.hibernate.SQL: debug
    # org.hibernate.orm.jdbc.bind: trace

# C:\'Program Files (x86)'\H2\bin
# jdbc:h2:mem:test
